### ISSUE TITLE
Show venues

### ISSUE THREAD

**Issue by christiankn** [oslopride/oslopride-website#120]
Venues are defined in sanity and represent specific locations, like a certain stage within Pride Park or a conference-room in Pride House. 

These are only assignable by editors:
- Give necessary training to editors, since this is structured content
- Display information on the event

**Comment by siddise** [comment]
#129 Fixed such that venue is displayed through "name" and address in Sanity. However we want some logic where: 

Få frem arena (eks Pride Park) og område. Hvis det gjelder eksterne (Eksterne arenaer), vises Navn (ikke område).
Oslo Pride event = Pride Park, Hovedscenen
Eksternt event = Ekstern arena, Oslo Domkirke
