### ISSUE TITLE
Change menu design

### ISSUE THREAD

**Issue by siddise** [oslopride/oslopride-website#137]
>"Program 2019" har blitt oppfattet av noen som overskrift, og så har de klikket seg inn på ønsket arena "Pride Park" og ikke forstått hvorfor det bare står en generell beskrivelse og ikke noe program.

**Comment by siddise** [comment]
@christiankn kanskje jeg skal lage en megamenu som foreslått i #92 når jeg først er i gang med dette issuet?

**Comment by christiankn** [comment]
Den ser knall ut på mobil, hvordan vil den se ut på desktop?

**Comment by siddise** [comment]
> Den ser knall ut på mobil, hvordan vil den se ut på desktop?

Har oppdatert Sketch dokumentene i [lenken](https://sketch.cloud/s/wwJYE/p/megamenu).Tanken at den skal komme fra høyre og være fixed på skjermstørrelsen.

**Comment by christiankn** [comment]
Ikke 100% solgt på desktop-versjonen, men det er vanskelig å se uten å prøve det live. 
Ser megamenyen har samme problem som dagens meny med program-overskrift 🤔

**Comment by boyeborg** [comment]
Jeg er heller ikke helt fan av den "fra siden"-varianten. Jeg liker bedre når det oppfører seg likt på mobil og desktop egentlig. Sånn som hos https://www.politiet.no

**Comment by christiankn** [comment]
Enig, så kan vi eventuelt bruke den ekstra plassen til headlinere eller annet snacks

**Comment by boyeborg** [comment]
Ja, det er ikke dumt. Snike med litt info om program hvor vi kan!

Jeg tenker også at når du trykker på menyen så fant du ikke det du lette etter på siden, så jeg ser ikke at det er noe verdi å prøve å vise resten av siden mens du ser på menyen. Menyen burde være i hovedfokus når du trykker på den, ikke helt til venstre på skjermen

**Comment by siddise** [comment]
har endret designet slik at den fyller rommet under headeren, slik som på politiet.no. 
Da har vi mye space som vi kan leke med når vi trenger det
