### ISSUE TITLE
Change ratio of images on eventlist

### ISSUE THREAD

**Issue by siddise** [oslopride/oslopride-website#190]
Fra Trello:

> 
> Siden vi ikke har kommunisert krav om bildeformat til tredjeparter har det kommet inn en del klager til kommunikasjon på hvordan bildene kuttes på nettsiden. Et kompromiss er å lene oss på kjente format, som 4:3 og 16:9, da er det større sjanse for at bildene ser OK ut.
> 
> Derfor er et forslag å gjøre programlistebildene 4:3 og programsidebildene 16:9. Det er bare snakk om en liten justering på dagens dimensjoner for å treffe formatene
>

**Comment by boyeborg** [comment]
Det er vel det samme bildet som vises både som thumbnails og på selve programmet, så det vil vel ikke nødvendigvis hjelpe å endre til 4:3 og 16:9? Om de legger inn et 16:9-bilde så ser det vel ikke alltid bra ut i 4:3?
Uansett, dette er jo derfor hotspot-funksjonen finnes i Sanity. Så man manuelt på hvert bilde kan si hvor hovedfokuset på bildet er.
