### ISSUE TITLE
SEO: Ensure search-ranking remains equivalent to existing site

### ISSUE THREAD

**Issue by christiankn** [oslopride/oslopride-website#22]
Use "Interpride AGM" as an example. Google-ranking should not decrease significantly when compared to today's server-side rendered site.

Bring any keywords from the old templates.

**Comment by boyeborg** [comment]
https://www.garymeehan.ie/blog/handling-seo-with-nextjs-and-prismic

**Comment by boyeborg** [comment]
This seems easy enough: https://github.com/garmeeh/next-seo
