### ISSUE TITLE
Adjust front-page layout to match today's style

### ISSUE THREAD

**Issue by christiankn** [oslopride/oslopride-website#64]
- Heart should be smaller, and text larger in hero-section
- Text in call-to-action and important dates should be bigger
- Header and content should be aligned

**Comment by boyeborg** [comment]
Would something like this be sufficient? Or should it be identical?

<img width="1792" alt="Screenshot 2019-03-21 at 21 02 00" src="https://user-images.githubusercontent.com/6630430/54781489-b3bfd680-4c1c-11e9-9056-250aa4f74d69.png">

**Comment by christiankn** [comment]
Doesn't have to be identical, but the grid should be similar. If you center-align the heart over "hoveddatoer" I think it looks good. (And also left-align the call-to-actions).
