### ISSUE TITLE
Max width on images in block content

### ISSUE THREAD

**Issue by boyeborg** [oslopride/oslopride-website#65]
Currently, block content containing images just renders the full image. This is not necessary. We should limit the width to 1000px. And perhaps do some other optimizations. Perhaps limit the image size in sanity?

**Comment by christiankn** [comment]
Doesn't sanity provide whichever size we ask for?

**Comment by boyeborg** [comment]
yeah, but the package rendering block content doesn't ask for any specific width, hence we get the full width. We need to change this behavior, such that when building image URLs we include the `maxWith(1000)`-option.
